# Generated by Django 5.1.4 on 2025-06-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_country_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(max_length=150),
        ),
    ]
