# Generated by Django 5.1.4 on 2025-05-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
