# Generated by Django 5.1.4 on 2025-05-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
