# Generated by Django 5.1.4 on 2025-06-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
