# Generated by Django 5.1.4 on 2025-06-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_order_is_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Order', 'verbose_name_plural': 'Customer Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Ordered Item', 'verbose_name_plural': 'Ordered Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Store Product', 'verbose_name_plural': 'Store Products'},
        ),
    ]
